//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template4335
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERS
    {
        public int ZakazId { get; set; }
        public string ZakazCode { get; set; }
        public string ZakazCreationDate { get; set; }
        public string ZakazTime { get; set; }
        public string ClientCode { get; set; }
        public string ZakazUslugi { get; set; }
        public string ZakazStatus { get; set; }
        public string ZakazClosureDate { get; set; }
        public string ZakazProkatTime { get; set; }
    }
}
