//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template4335
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uslugi
    {
        public int Id { get; set; }
        public string CodeZakaz { get; set; }
        public string Date { get; set; }
        public string TimeZakaz { get; set; }
        public string CodeClient { get; set; }
        public string Uslugi1 { get; set; }
        public string Status { get; set; }
        public string DateOff { get; set; }
        public string TimeProkat { get; set; }
    }
}
