//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template4335
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        public string id_worker { get; set; }
        public string status { get; set; }
        public string fio { get; set; }
        public string login { get; set; }
        public string pass { get; set; }
        public string lastenter { get; set; }
        public string entertype { get; set; }
    }
}
